name: 02 Basics - events

on: [push, pull_request]

jobs:
    print-hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: Print Hello World
              run: echo "Hello, World!"