name: 06 Basics Context
run-name: ${{ github.actor }} Explaing Context Data
on: 
    workflow_dispatch
        
jobs:
    print-hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: Print Context Data
            #   run: echo ${{ github.event_name }} ${{ github.actor }} ${{ github.repository }} ${{ github.workflow }}
              run: echo ${{ toJson(github) }}
            #   run: echo ${{ job.status }} 